version: '3'
services:
  apache-php:  
    build: .
    container_name: apache-php
    volumes:
      - ./src:/var/www/html/
    ports:
      - "80:80"
    extra_hosts:
      - "dockerhost:192.168.70.116"